### ISSUE TITLE
Full Names

### ISSUE THREAD

**Issue by hughbe** [nori0620/SwiftPathClass#11]
Abbreviations, whilst more brief than fully qualified names are ugly and are not necessary in an autoccompleted language such as swift in Xcode. 

Even Apple's API design guidelines suggest avoiding short abbreviations for properties etc.

Therefore, you could consider, and I would be happy to provide a pull request, replacing these ugly and perhaps even confusing abbreviations with fully qualified names. 

E.g mkdir becomes makeDirectory and so on
This would be a breaking change.

**Comment by SeeBenClick** [comment]
mkdir is arguably more readable than makeDirectory because it matches the shell command name
